<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">Import Data From Excel or CSV File to Mysql using PHPSpreadsheet</div>
        <br>
        <div class="panel-body">
            <div class="table-responsive">
                <span id="message"></span>
                <form method="post" id="import_excel_form" enctype="multipart/form-data" action="http://magento.local/admin/helloworld/import/check">
                    <input type="file" name="import_excel" />
                    <br>
                    <br>
                    <button type="submit" class="btn btn-primary btnImport">Import</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    const formImport = document.getElementById("import_excel_form");

    formImport.addEventListener("submit",async function(e){
        e.preventDefault();
        console.log("start");

        const formData = new FormData(this);

        await fetch('http://magento.local/admin/helloworld/import/check', {
            method: 'POST',
            body: formData
        }).then(function (response) {
            return response.text();
        }).then(function (res) {
            console.log(res);
        });
    });
</script>
